### PR TITLE
Embedded intent standards

### PR DESCRIPTION
**Pull request by supiket**
## Changes
`EntryPoint` has the structure:
```
contract EntryPoint
├─ interface IEntryPoint
├─ abstract contract NonceManager
└─ abstract contract IntentValidatorExecutor
   ├─ interface IIntentValidatorExecutor
   ├─ abstract contract ReentrancyGuard
   ├─ abstract contract EmbeddedIntentStandards
   └─ abstract contract IntentStandardRegistry
      └─ interface IIntentStandardRegistry

```

`EmbeddedIntentStandards` has the structure:
```
abstract contract EmbeddedIntentStandards
├─ function isEmbeddedIntentStandard
├─ function _validateIntentSegment
└─ function _executeIntentSegment
```

`IntentStandard`s are implementations of `BaseIntentStandard`s which in turn define internal functions for validating and executing intents. 
To create the corresponding standard that is embeddable to the entry point, the embeddable standard contract should define its ID and expose a method that is not in a naming clash with other embedded standards (this is managed by `EmbeddedIntentStandards`). 
To create the corresponding standard that is deployable, the deployable standard contract should implement the `IDeployableIntentStandard` interface which wraps the validation and execution methods with external methods that can be called by the entry point.
`EmbeddedIntentStandards` extends all embedded standards and overrides their `_validateIntentSegment` and `_executeIntentSegment` functions to call the respective method of the specific standard.

### CODE REVIEW

**Comment by supiket** [comment]
`BaseIntentStandard` is an abstract contract because it only has internal methods, though it acts as an interface for implementing core functionality for either embeddable or deployable standards. For this reason, it is in the `interfaces` folder.

**Comment by pixelcircuits** [comment]
Can we combine the "base", "deployable", and "embedded" versions of files all into one? 

Also, I think we should avoid the name "deployable" and just refer to things as the core standard (ex. `IDeployableIntentStandard` -> `IIntentStandard`, `DeployableEthRequireExponential` -> `EthRequireExponential`). My reasoning is that the embedding concept is just an extension to ERC-7521. I like to think that the intent standard contracts could be copied to a version of the entrypoint that doesn't do embedding. The same intent standard can now be registered to multiple entrypoints too

**Comment by supiket** [comment]
- Combined the base, embeddable and deployable contracts in a single file for each standard
- Added deployable versions of embedded contracts (even though they are not used in our implementation of `IEntryPoint`)
  - However, not every base standard has an embeddable version implemented, only the ones that are embedded in our implementation. Thoughts?
- Applied the renaming suggestion
- Fixed some comments 

Also any thoughts on the choice of embedded standards: `SimpleCall`, `UserOperation`, `EthRecord`, `EthRequire`, `EthRelease` is appreciated :)

**Comment by supiket** [comment]
Can also consider `Embeddable` -> `Internal`, maybe it is too vague though

**Comment by pixelcircuits** [comment]
> Can also consider `Embeddable` -> `Internal`, maybe it is too vague though

Yeah, `internal` feels too generic like since it's a visibility keyword in solidity

**Comment by pixelcircuits** [comment]
We'll probably want to embed all intent standards we make for our base case scenarios. The only thing stopping us the the contract code size.

**Comment by pixelcircuits** [comment]
I'm not sure why you split out "IntentValidatorExecutor" and "IntentStandardRegistry" from the EntryPoint since that seems very core to the EntryPoint. I feel like it makes sense to isolate features labeled as "extensions" in the spec as their own contract like "NonceManager" and "EmbeddedIntentStandards" though. At the very least, they don't need interfaces specified in `interfaces`.

**Comment by supiket** [comment]
> I'm not sure why you split out "IntentValidatorExecutor" and "IntentStandardRegistry" from the EntryPoint since that seems very core to the EntryPoint. I feel like it makes sense to isolate features labeled as "extensions" in the spec as their own contract like "NonceManager" and "EmbeddedIntentStandards" though. At the very least, they don't need interfaces specified in `interfaces`.

I agree with your point about extensions. 
My reasoning was to split the EntryPoint's core features, rather than thinking of IntentValidatorExecutor and IntentStandardRegistry as extensions like NonceManager and EmbeddedIntentStandards.

Acting as a standard registry and validating and executing intents can be thought of as two separate core features.
IntentValidatorExecutor contains the implementation details of the interface defined by IEntryPoint. I see that this may be going overboard. 
I do not think that this is the case for splitting the standard registry feature, on the other hand I see your point about these being very core to the EntryPoint.

So I can take these changes back if splitting these is confusing / unnecessary.

**Comment by pixelcircuits** [comment]
The 4337 ref impl breaks out the nonce manager, stake manager and simulations into their own contracts. All of those also have interfaces in the "interfaces" folder. I think it's fine if the registry stays split as long as the interface is also split, which you did do

**Review by pixelcircuits — APPROVED** [review]

**Pull request merged**
